apiVersion: v1
kind: Service
metadata:
  name: keytab-gen-service
  labels:
    app: keytab-gen-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: keytab-gen-app
